apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dns-resolver-data
  namespace: house-infra
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 2Gi
